events {}

http {

    log_format custom_json escape=json
    '{'
        '"time":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":$status,'
        '"request_time":$request_time'
    '}';

    access_log /var/log/nginx/access.log custom_json;
    error_log /var/log/nginx/error.log;

    upstream api_backend {
        server api:5000;
    }

    server {
        listen 80;

        location / {
	   # generate request id if missing
            proxy_set_header X-Request-ID $request_id;
           
	    proxy_pass http://api_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
