events {}

http {

    upstream api {
        server python_api:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api;

            # ----------------------------
            # Basic Proxy Headers
            # ----------------------------
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # ----------------------------
            # Observability Header (IMPORTANT)
            # ----------------------------
            proxy_set_header X-Request-ID $http_x_request_id;

            # ----------------------------
            # Timeouts (stability)
            # ----------------------------
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
        }
    }
}
