apiVersion: 1

datasources:
  - name: Loki
    type: loki
    # Proxy access (Grafana server connects to Loki server)
    access: proxy
    # Loki container address in the Docker network
    url: http://loki:3100
    isDefault: false
    # Prevent manual edits in Grafana UI
    editable: false
