---
- name: Deploy Python API and Nginx Stack
  hosts: webservers
  become: yes
  vars:
    dest_dir: /opt/python-api-docker

  tasks:
    - name: Ensure application directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files to production directory (excluding unnecessary files)
      ansible.builtin.synchronize:
        src: "{{ playbook_dir }}/../"  # Source path of the project on the local machine/runner
        dest: "/opt/python-api-docker"
        delete: yes                    # Remove outdated files from the destination directory
        exclude:
          - ".git"
          - ".github"
          - "docs"
          - "*.md"
          - "tree.txt"
          - "ansible"
      delegate_to: localhost          # Run the synchronization task from the runner/localhost

    - name: Set correct permissions for Prometheus data
      file:
        path: "{{ dest_dir }}/prometheus_data"
        state: directory
        owner: "65534"
        group: "65534"
        recurse: yes

    - name: Set correct permissions for Loki data
      file:
        path: "{{ dest_dir }}/loki_data"
        state: directory
        owner: "10001"
        group: "10001"
        recurse: yes

    - name: Deploy stack with 2 application replicas
      command: docker compose up -d --scale app=2
      args:
        chdir: "{{ dest_dir }}"
