[webservers]
#localhost ansible_connection=local
#-----------------------------------------------
#if use another remote server over SSH
#192.168.X.X ansible_port=22 ansible_user=username ansible_connection=ssh
127.0.0.1 ansible_port=22 ansible_user=alborz ansible_connection=ssh
#----------------------------------------------
